return {
	Tokenizer = {
		toFormat = "#", -- Prefix before tokenizing | "#H:#M:#S" -> {"#H", "#M", "#S"}

		resultShouldIncludeUnknownTokens = true,
	},

	tokensRequiringFormatting = {
		-- Formatting includes: 0 in front of lonely numbers
		"hour_24",
		"minute",
		"second",
	},

	timesTable = {
		{ "Year", "y", 31536000 },
		{ "Month", "mo", 2628000 },
		{ "Week", "w", 604800 },
		{ "Day", "d", 86400 },
		{ "Hour", "h", 3600 },
		{ "Minute", "m", 60 },
		{ "Second", "s", 1 },
	},

	addOrRemoveTypes = {
		"second",
		"seconds",
		"minute",
		"minutes",
		"hour",
		"hours",
		"day",
		"days",
		"week",
		"weeks",
		"month",
		"months",
		"year",
		"years",
	},

	Patterns = {
		["h"] = { expectedType = "hour_12", Type = "number" },
		["hh"] = { expectedType = "hour_24", Type = "number" },
		["m"] = { expectedType = "minute", Type = "number" },
		["s"] = { expectedType = "second", Type = "number" },
		["ms"] = { expectedType = "millis", Type = "number" },

		["mm"] = { expectedType = "month", Type = "number" },
		["mmm"] = { expectedType = "month_short", Type = "string" },
		["mmmm"] = { expectedType = "month_long", Type = "string" },

		["d"] = { expectedType = "day_num", Type = "number" },
		["dd"] = { expectedType = "day_short", Type = "string" },
		["ddd"] = { expectedType = "day_long", Type = "string" },

		["yd"] = { expectedType = "year_day", Type = "number" },
		["myd"] = { expectedType = "max_year_days", Type = "number" },
		["yy"] = { expectedType = "year_short", Type = "number" },
		["yyyy"] = { expectedType = "year_long", Type = "number" },

		["w"] = { expectedType = "week_day", Type = "number" },
		["ww"] = { expectedType = "week_year", Type = "number" },

		["u"] = { expectedType = "unix", Type = "number" },
		["uu"] = { expectedType = "unix_ms", Type = "number" },

		["z"] = { expectedType = "timezone", Type = "string" },
		["a"] = { expectedType = "ampm", Type = "string" },
	},

	Names = {
		weekDays = {
			"Sunday",
			"Monday",
			"Tuesday",
			"Wednesday",
			"Thursday",
			"Friday",
			"Saturday",
		},

		Months = {
			"January",
			"February",
			"March",
			"April",
			"May",
			"June",
			"July",
			"August",
			"September",
			"October",
			"November",
			"December",
		},
	},

	timezonesIgnoreDST = {
		"UTC",
		"GMT",
		"WET",
		"CVT",
		"AZOST",
		"GST",
		"WGST",
		"EGST",
		"FNT",
		"BRST",
		"BRT",
		"FKST",
		"UYT",
		"ART",
		"CLST",
		"PYT",
		"BOT",
		"GYT",
		"AMT",
		"VET",
		"CST",
		"EST",
		"AST",
		"NST",
		"PMST",
	},

	Timezones = {
		-- Format: [timeZoneName] = to_add_to_GMT
		-- Types: [string] = number

		["UTC"] = 0,
		["GMT"] = 0,
		["WET"] = 0,
		["CVT"] = -1,
		["BST"] = 1,
		["CET"] = 1,
		["WEST"] = 1,
		["EET"] = 2,
		["CEST"] = 2,
		["EEST"] = 3,
		["MSK"] = 3,
		["TRT"] = 3,
		["AST"] = 3,
		["GST"] = 4,
		["MUT"] = 4,
		["RET"] = 4,
		["SCT"] = 4,
		["AMT"] = 4,
		["AZT"] = 4,
		["GET"] = 4,
		["SAMT"] = 4,
		["AFT"] = 4.5,
		["IRST"] = 5,
		["AZST"] = 5,
		["YEKT"] = 5,
		["ORAT"] = 5,
		["PKT"] = 5,
		["MMT"] = 6.5,
		["IST"] = 5.5,
		["UZT"] = 5,
		["AQTST"] = 5,
		["AQTT"] = 5,
		["KGT"] = 6,
		["BDT"] = 6,
		["BIOT"] = 6,
		["NPT"] = 5.75,
		["ALMT"] = 6,
		["MMST"] = 6,
		["KRAT"] = 7,
		["NOVST"] = 7,
		["WIB"] = 7,
		["THA"] = 7,
		["ICT"] = 7,
		["HOVT"] = 7,
		["WITA"] = 8,
		["HKT"] = 8,
		["ULAT"] = 8,
		["MALST"] = 8,
		["AWST"] = 8,
		["WST"] = 8,
		["IRKT"] = 8,
		["CST"] = 8,
		["JST"] = 9,
		["KST"] = 9,
		["YAKST"] = 9,
		["EAST"] = 10,
		["AEST"] = 10,
		["VLAST"] = 11,
		["SAKT"] = 11,
		["NCT"] = 11,
		["SBT"] = 11,
		["FJT"] = 12,
		["NZST"] = 12,
		["PETT"] = 12,
		["ANAST"] = 12,
		["MAGT"] = 12,
		["FJST"] = 13,
		["NZDT"] = 13,
		["CHADT"] = 13.75,
		["PHOT"] = 13,
		["WAKT"] = 12,
		["CHAST"] = 12.75,
		["SST"] = 11,
		["LINT"] = 14,
		["TOT"] = 13,
		["AZOT"] = -1,
		["EGST"] = 0,
		["AZOST"] = 0,
		["WAT"] = 1,
		["FET"] = 3,
		["CAT"] = 2,
		["IRDT"] = 5.5,
		["QYZT"] = 6,
		["BNT"] = 8,
		["CHOT"] = 8,
		["KRAST"] = 8,
		["SGT"] = 8,
		["YAKT"] = 9,
		["AEDT"] = 11,
		["VLAT"] = 11,
		["PETST"] = 13,
		["MAGST"] = 12,
		["WFT"] = 12,
		["Hovd Time"] = 7,
		["Fakaofo Time"] = 13,
		["Chatham Standard Time"] = 12.75,
		["Tonga Standard Time"] = 13,
		["Apia Standard Time"] = 14,
		["Apia Daylight Time"] = 14,
		["Samoa Standard Time"] = 13,
		["Samoa Daylight Time"] = 14,
		["Line Islands Time"] = 14,
	},
}
